services:
  app:
    image: simple2b/drive-smart
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drivesmartuae.rule=Host(`drivesmartuae.com`) || Host(`www.drivesmartuae.com`) || Host(`drive-smart.simple2b.net`)"
      - "traefik.http.routers.drivesmartuae.tls=true"
      - "traefik.http.routers.drivesmartuae.tls.certresolver=myresolver"
